### PR TITLE
Admin destination tabs

### PR DESCRIPTION
**Pull request by mammuth**
This PR adds horizontal tabs for the four mutually exclusive destinations which results in a much smaller and cleaner admin UI.

link2-destination-admin

Possible ToDo for the future: When editing an existing link, the tab with the set destination should be active.

### CODE REVIEW

**Comment by SteinRobert** [comment]
@mammuth interesting idea! I think this might cause some usability issues. At the moment it is possible to set URL, page link, mail and file all at once. Having tabs this might cause users to think they have set the right link (or page, mail, file), even though something else is set two.
So either we override the `clean` method, so that the user can fill out only one of those field, or we find another way to make the admin more neat.
This probably needs more discussion.

**Comment by mammuth** [comment]
Ah, I didn't notice that the model currently indeed allows the user to set multiple destinations at once. 

I'm not able to find a use case where multiple destinations make sense, so we might correct that in the `clean` method.

**Comment by SteinRobert** [comment]
I agree. In that case it we should make sure set the correct tab active (what you suggested as possible future ToDo).
Adopting the `clean` method and setting the filled-out-value-tab would make that a cool feature I think.

**Comment by mammuth** [comment]
I changed it, so that only one destination is allowed when saving and a corresponding error message is shown when there are multiple destinations set.

Also, the tab of the set destination is active now. If a new plugin instance is created, the first tab (url) is active.
only allow one destination

**Review by SteinRobert — APPROVED** [review]
LGTM

**Pull request merged**
